name: alioss

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: "12.x"
#      - name: Build Blog
#        run: |
#          npm install
#          npm install -g hexo-cli
#          hexo generate
      - name: find path
        run: |
          pwd
      - uses: manyuanrong/setup-ossutil@v1.0
        with:
          # endpoint 可以去oss控制台上查看
          endpoint: "oss-cn-hongkong.aliyuncs.com"
          # 使用我们之前配置在secrets里面的accesskeys来配置ossutil
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
          #sts-token: "sts_token"
      - name: Deply To OSS
        run: ossutil cp ./ oss://blog-myki/ -rf
